# Generated by Django 4.2.4 on 2023-12-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='keycloak_id',
        ),
    ]
