# Generated by Django 4.2.4 on 2023-12-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_account_keycloak_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='keycloak_id',
            field=models.CharField(default='aa', max_length=50),
            preserve_default=False,
        ),
    ]
