# Generated by Django 4.2.4 on 2023-10-06 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True)),
                ('manage_date', models.DateField(blank=True)),
                ('test_name', models.TextField(blank=True, null=True)),
                ('subject_name', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('etc', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True)),
                ('manage_date', models.DateField(blank=True)),
                ('current', models.TextField(blank=True, null=True)),
                ('remain_test_area', models.TextField(blank=True, null=True)),
                ('comma', models.CharField(blank=True, max_length=255, null=True)),
                ('school_grade_data', models.DateField(blank=True, null=True)),
                ('cm_backup', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_instruct_room', models.CharField(blank=True, max_length=255, null=True)),
                ('Textbook_explanation', models.BooleanField(blank=True, default=False, null=True)),
                ('etc', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='student_manage.studentrecord')),
            ],
        ),
    ]
