# Generated by Django 4.2.5 on 2023-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('enrollment_date', models.DateField()),
                ('is_enrolled', models.BooleanField(default=True)),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
