# Generated by Django 4.2.4 on 2023-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='guardian_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_phone_number',
            new_name='father_phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
